apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption
  namespace: utility
  labels:
    app: encryption
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encryption
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: encryption
        env: charite
    spec:
      containers:
        - name: encryption
          image: s-hdp-vre-v007.charite.de/encryption:<VERSION>
          ports:
            - containerPort: 5082
          env:
          - name: env
            value: "charite"
          - name: CONFIG_CENTER_ENABLED
            value: "true"
          - name: CONFIG_CENTER_BASE_URL
            value: "http://common.utility:5062/"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1"
            limits:
              memory: "1000Mi"
              cpu: "1"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: encryption
  namespace: utility
  labels:
    app: encryption
    env: charite
spec:
  ports:
  - name: http
    port: 5082
    targetPort: 5082
  selector:
    app: encryption
    env: charite
  type: ClusterIP
